kind: Deployment
apiVersion: apps/v1
metadata:
  name: greenstage
  namespace: default
  labels:
    app: blue-green
spec:
  replicas: 1
  selector:
    matchLabels:
      app: blue-green
      version: v2
  template:
    metadata:
      labels:
        app: blue-green
        version: v2
    spec:
      containers:
      - name: blue-green
        imagePullPolicy: Always
        image: "viraj5132/bluegreen:latest"
        ports:
          - containerPort: 3000
# ---
# apiVersion: v1
# kind: Service
# metadata:
#   name: greenstage
#   namespace: default
# spec:
#   selector:
#     app: greenstage
#   type: NodePort
#   ports:
#   - name: http
#     targetPort: 3000
#     port: 80