kind: Deployment
apiVersion: apps/v1
metadata:
  name: bluestage
  namespace: default
  labels:
    app: blue-green
spec:
  replicas: 1
  selector:
    matchLabels:
      app: blue-green
      version: v1
  template:
    metadata:
      labels:
        app: blue-green
        version: v1
    spec:
      containers:
      - name: blue-green
        imagePullPolicy: Always
        image: "viraj5132/bluegreen:latest"
        ports:
          - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: blue-green
  namespace: default
spec:
  selector:
    app: blue-green
    version: v1
  type: NodePort
  ports:
  - name: http
    targetPort: 3000
    port: 80